Module 1 Capstone project
Yothu/module-1-capstone-project pull request #2
Opened 2021-12-18 21:14 UTC by Yothu

2021-12-23 21:05 UTC, MrBrN197 requested changes
## Hi, @Yothu  👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔Great Design
- ✔ Professional Video

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 21:05 UTC, MrBrN197 commented on index.html
> +            <div class="header-x-padding container-fluid d-flex justify-content-between max-content-width inner-header-container">
- [x] Hi, I'd like to inform you that the navbar should be transparent in the mobile version according to the reference design. please implement this change. it's for the mobile version only
## Your Design
![image](https://user-images.githubusercontent.com/18730106/147287927-3af554fe-dbfe-44f2-870f-516ecc4edb1c.png)

## Reference Design
![image](https://user-images.githubusercontent.com/18730106/147288011-e0f5eb5a-3589-43bc-9e44-61a78f8fdd7a.png)

2021-12-23 21:05 UTC, MrBrN197 commented on index.html
> +            <div class="header-x-padding container-fluid d-flex justify-content-between max-content-width inner-header-container">
- [x] Hi, can you kindly ensure that the navbar on the desktop version has the top part that is available on the design 
## Black bar atop the navbar
![image](https://user-images.githubusercontent.com/18730106/147288126-9e943425-41e7-4246-a9b8-712462226f21.png)
You don't have the black section on your desktop version please implement this change as per the reference design.
- [x] Make sure they are aligned correctly to the right.

2021-12-23 21:05 UTC, MrBrN197 commented on css/main-style.scss
> +$red: #ec5242;
Great work making use of the colors used in the design 👏👏

2021-12-23 21:05 UTC, MrBrN197 commented on index.html
> +      </div>
- [x] Hi the design of this section is nice. I'd however, like you to ensure you use a `<footer />` tag to signify this section instead of a `<div />` it makes more sense semantically to contain this section in a `footer`. let's try to adhere to correct HTML semantics
- [x] do the same thing on the about page

2021-12-23 21:05 UTC, MrBrN197 commented on pages/about.html
> +      </div>
- [x] Hi, please kindly notice that the design of this section on the desktop version has a dark background. please implement this change so that the footer has a dark background.
## Your Design 
![image](https://user-images.githubusercontent.com/18730106/147288607-8ae82070-b2e0-4c2e-909a-6d9e08697533.png)

## Reference Design 
![image](https://user-images.githubusercontent.com/18730106/147288592-5e448905-2d59-4411-afc9-37b38db1dafc.png)

2021-12-23 21:05 UTC, MrBrN197 commented on pages/about.html
> +      </div>
- [x] Hi the design of this section is nice. I'd, however, like you to ensure you use a `<footer />` tag to signify this section instead of a `<div />` it makes more sense semantically to contain this section in a `footer`. let's try to adhere to correct HTML semantics

2021-12-24 00:19 UTC, mmsesay approved these changes
Hi @Yothu, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-12-24 00:19 UTC, mmsesay commented on index.html
> +    </section>
- [ ] [OPTIONAL] This section's background image is not aligned to the original design.

Your Design       |Original Design   |
:--------------------:|:---------------------:|
![e1](https://user-images.githubusercontent.com/39523312/147301115-0b091009-b3e9-4caf-99d3-f3045480512b.png)| ![e2](https://user-images.githubusercontent.com/39523312/147301134-cadfd631-85d3-494f-baf8-bedf6506e207.png) |

2021-12-24 00:33 UTC, merged